version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'broadcaster'
       MYSQL_USER: 'development'
       MYSQL_PASSWORD: 'development'
       MYSQL_ROOT_PASSWORD: 'development'
    volumes:
      - ~/mysql_game_server_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - '6379:6379'
  game-server:
    image: game-server
    # volumes:
      # - "</path/to/app/subdir>:/app/<subdir>"
    ports:
      - "9000:9000"
      - "8080:8080"
    depends_on:
      - mysql
      - redis


# docker run -d -p 6379:6379 redis
# docker run -d -v ~/mysql_game_server_data:/var/lib/mysql -p 3306:3306 mysql:5.7